services:
  db:
    image: postgres:16
    container_name: lead_management_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - lead_management_network
    env_file:
      - '.env'
  web:
    build: .
    container_name: lead_management_web
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8004"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8004:8004"
    depends_on:
      - db
      - redis
    networks:
      - lead_management_network
    env_file:
      - '.env'

  redis:
    image: redis:alpine
    container_name: lead_management_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lead_management_network

  celery:
    container_name: lead_management_celery
    build: .
    command: celery -A core worker -l info
    volumes:
      - static_volume:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: always
    networks:
      - lead_management_network


volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data:

networks:
   lead_management_network:
     driver: bridge