# Generated by Django 5.2.1 on 2025-05-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('email', models.EmailField(max_length=125, verbose_name='email')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='resume/cv')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reached_out', 'Reached Out')], default='pending', max_length=60, verbose_name='status')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
            },
        ),
    ]
